### ISSUE TITLE
Cursor not blinking anymore

### ISSUE THREAD

**Issue by cyrus-** [hazelgrove/hazel#427]
recent regression

**Comment by dm0n3y** [comment]
Dug a bit into this. I think this is caused by an incr_dom change where now the MVU loop runs on every animation frame instead of just when an update is queued https://github.com/janestreet/incr_dom/blob/master/src/start_app.ml#L387. Setting aside for now.

**Comment by cyrus-** [comment]
That sounds inefficient...

**Comment by dedbox** [comment]
For what it's worth, we use CSS to make the cursor blink in Grove. In our case, by cycling visibility of border-left.

```css
@keyframes blink-left {
    50% {
        border-left: 1px solid black;
        margin-left: -1px;
    }
}

.editor:focus .cursor > .hole:only-child {
    animation-name: blink-left;
    animation-duration: .5s;
    animation-timing-function: step-end;
    animation-iteration-count: infinite;
    animation-direction: alternate;
}
```
